import { DUNGEONS, ECONOMIC_TYPES } from "../../entities";

export const AVAILABLE_QUESTS_TYPES = [
  DUNGEONS.CATCH_GOBLIN,
  DUNGEONS.CLOSE_PORTAL,
  DUNGEONS.FIND,
];

export const AVAILABLE_ECONOMIC_TYPES = [
  ECONOMIC_TYPES.ALCHEMISTRY,
  ECONOMIC_TYPES.FISHING,
  ECONOMIC_TYPES.WEAPONRY,
];
