import { SPECIAL_ENCOUNTERS } from "../../entities/specialEncounters";

export const DEFAULT_SPECIAL_ENCOUNTERS_LIST = [
  SPECIAL_ENCOUNTERS.GHOST,
  SPECIAL_ENCOUNTERS.SHOOTING,
  SPECIAL_ENCOUNTERS.TRADER,
];
