import { POTION_TYPES } from "../../entities/consumables";
import { JUNK_TYPES } from "../../entities/junk";

export const JUNK_DATA = {
  [JUNK_TYPES.AXE]: {
    price: 200,
    title: "Декоративный топорик",
  },
  [JUNK_TYPES.CHEMICAL_HEATING_PAD]: {
    price: 200,
    title: "Химическая горелка",
  },
  [JUNK_TYPES.SLEEPING_BAG]: {
    price: 200,
    title: "Спальный мешок",
  },

  [JUNK_TYPES.CRYSTAL_ORB]: {
    price: 300,
    title: "Кристальный шар",
  },
  [JUNK_TYPES.JEWELRY_BOX]: {
    price: 300,
    title: "Шкатулка с драгоценностями",
  },
  [JUNK_TYPES.GLASSES]: {
    price: 300,
    title: "Очки",
  },

  [JUNK_TYPES.GOLDEN_CHAIN]: {
    price: 500,
    title: "Золотая цепочка",
  },
  [JUNK_TYPES.BROKEN_RADIOSTATION]: {
    price: 500,
    title: "Сломанная радиостанция",
  },
  [JUNK_TYPES.BROKEN_PC]: {
    price: 500,
    title: "Сломанный компьютер",
  },
};

export const FIRST_TIER_JUNK = [
  JUNK_TYPES.AXE,
  JUNK_TYPES.CHEMICAL_HEATING_PAD,
  JUNK_TYPES.SLEEPING_BAG,
];
export const SECOND_TIER_JUNK = [
  JUNK_TYPES.CRYSTAL_ORB,
  JUNK_TYPES.JEWELRY_BOX,
  JUNK_TYPES.GLASSES,
];
export const THIRD_TIER_JUNK = [
  JUNK_TYPES.GOLDEN_CHAIN,
  JUNK_TYPES.BROKEN_RADIOSTATION,
  JUNK_TYPES.BROKEN_PC,
];

export const POTION_TIERS = {
  [POTION_TYPES.SMALL_HEALTH_POTION]: 1,
  [POTION_TYPES.MEDIUM_HEALTH_POTION]: 2,
  [POTION_TYPES.LARGE_HEALTH_POTION]: 3,
  [POTION_TYPES.EXTRA_LARGE_HEALTH_POTION]: 4,
};

export const getPotionByTier = (currentTier: number) => {
  if (currentTier === 1) {
    return POTION_TYPES.SMALL_HEALTH_POTION;
  }

  if (currentTier === 2) {
    return POTION_TYPES.MEDIUM_HEALTH_POTION;
  }

  if (currentTier === 3) {
    return POTION_TYPES.LARGE_HEALTH_POTION;
  }

  return POTION_TYPES.EXTRA_LARGE_HEALTH_POTION;
};

export enum BASE_ITEMS_ID {
  GALVION_TIER_1 = "GALVION_TIER_1",
  GALVION_TIER_2 = "GALVION_TIER_2",
  GALVION_TIER_3 = "GALVION_TIER_3",
  HJELM_TIER_1 = "HJELM_TIER_1",
  HJELM_TIER_2 = "HJELM_TIER_2",
  HJELM_TIER_3 = "HJELM_TIER_3",
  ALTYN_TIER_1 = "ALTYN_TIER_1",
  ALTYN_TIER_2 = "ALTYN_TIER_2",
  ALTYN_TIER_3 = "ALTYN_TIER_3",
  MASKA_TIER_1 = "MASKA_TIER_1",
  MASKA_TIER_2 = "MASKA_TIER_2",
  MASKA_TIER_3 = "MASKA_TIER_3",
  RONIN_HELMET_TIER_1 = "RONIN_HELMET_TIER_1",
  RONIN_HELMET_TIER_2 = "RONIN_HELMET_TIER_2",
  RONIN_HELMET_TIER_3 = "RONIN_HELMET_TIER_3",
  RONIN_RESPIRATOR_TIER_1 = "RONIN_RESPIRATOR_TIER_1",
  RONIN_RESPIRATOR_TIER_2 = "RONIN_RESPIRATOR_TIER_2",
  RONIN_RESPIRATOR_TIER_3 = "RONIN_RESPIRATOR_TIER_3",
  BNTI_TIER_1 = "BNTI_TIER_1",
  NPP_TIER_1 = "NPP_TIER_1",
  BNTI_TIER_2 = "BNTI_TIER_2",
  BNTI_TIER_3 = "BNTI_TIER_3",
  NPP_TIER_2 = "NPP_TIER_2",
  NPP_TIER_3 = "NPP_TIER_3",
  IOTV_TIER_1 = "IOTV_TIER_1",
  IOTV_TIER_2 = "IOTV_TIER_2",
  IOTV_TIER_3 = "IOTV_TIER_3",
  FORT_TIER_1 = "FORT_TIER_1",
  FORT_TIER_2 = "FORT_TIER_2",
  FORT_TIER_3 = "FORT_TIER_3",
  NFM_TIER_1 = "NFM_TIER_1",
  NFM_TIER_2 = "NFM_TIER_2",
  NFM_TIER_3 = "NFM_TIER_3",
  REDUT_TIER_1 = "REDUT_TIER_1",
  REDUT_TIER_2 = "REDUT_TIER_2",
  REDUT_TIER_3 = "REDUT_TIER_3",
  SV98_TIER_1 = "SV98_TIER_1",
  SV98_TIER_2 = "SV98_TIER_2",
  SV98_TIER_3 = "SV98_TIER_3",
  DLV10_TIER_1 = "DLV10_TIER_1",
  DLV10_TIER_2 = "DLV10_TIER_2",
  DLV10_TIER_3 = "DLV10_TIER_3",
  AXMC_TIER_1 = "AXMC_TIER_1",
  AXMC_TIER_2 = "AXMC_TIER_2",
  AXMC_TIER_3 = "AXMC_TIER_3",
  MP155_TIER_1 = "MP155_TIER_1",
  MP155_TIER_2 = "MP155_TIER_2",
  MP155_TIER_3 = "MP155_TIER_3",
  REMINGTON_870_TIER_1 = "REMINGTON_870_TIER_1",
  REMINGTON_870_TIER_2 = "REMINGTON_870_TIER_2",
  REMINGTON_870_TIER_3 = "REMINGTON_870_TIER_3",
  SAIGA_TIER_1 = "SAIGA_TIER_1",
  SAIGA_TIER_2 = "SAIGA_TIER_2",
  SAIGA_TIER_3 = "SAIGA_TIER_3",
  AK_12_TIER_1 = "AK_12_TIER_1",
  AK_12_TIER_2 = "AK_12_TIER_2",
  AK_12_TIER_3 = "AK_12_TIER_3",
  M4A1_TIER_1 = "M4A1_TIER_1",
  M4A1_TIER_2 = "M4A1_TIER_2",
  M4A1_TIER_3 = "M4A1_TIER_3",
  SA58_TIER_1 = "SA58_TIER_1",
  SA58_TIER_2 = "SA58_TIER_2",
  SA58_TIER_3 = "SA58_TIER_3",
  MP5SD_TIER_1 = "MP5SD_TIER_1",
  MP5SD_TIER_2 = "MP5SD_TIER_2",
  MP5SD_TIER_3 = "MP5SD_TIER_3",
  FN_P90S_TIER_1 = "FN_P90S_TIER_1",
  FN_P90S_TIER_2 = "FN_P90S_TIER_2",
  FN_P90S_TIER_3 = "FN_P90S_TIER_3",
  KRISS_VECTOR_TIER_1 = "KRISS_VECTOR_TIER_1",
  KRISS_VECTOR_TIER_2 = "KRISS_VECTOR_TIER_2",
  KRISS_VECTOR_TIER_3 = "KRISS_VECTOR_TIER_3",
  GLOCK_17_TIER_1 = "GLOCK_17_TIER_1",
  GLOCK_17_TIER_2 = "GLOCK_17_TIER_2",
  GLOCK_17_TIER_3 = "GLOCK_17_TIER_3",
  FN_57_TIER_1 = "FN_57_TIER_1",
  FN_57_TIER_2 = "FN_57_TIER_2",
  FN_57_TIER_3 = "FN_57_TIER_3",
  DESERT_EAGLE_TIER_1 = "DESERT_EAGLE_TIER_1",
  DESERT_EAGLE_TIER_2 = "DESERT_EAGLE_TIER_2",
  DESERT_EAGLE_TIER_3 = "DESERT_EAGLE_TIER_3",
  RPD_TIER_1 = "RPD_TIER_1",
  RPD_TIER_2 = "RPD_TIER_2",
  RPD_TIER_3 = "RPD_TIER_3",
  M60_TIER_1 = "M60_TIER_1",
  M60_TIER_2 = "M60_TIER_2",
  M60_TIER_3 = "M60_TIER_3",
  PKM_TIER_1 = "PKM_TIER_1",
  PKM_TIER_2 = "PKM_TIER_2",
  PKM_TIER_3 = "PKM_TIER_3",

  HEALTH_ORB_TIER_1 = "HEALTH_ORB_TIER_1",
  HEALTH_ORB_TIER_2 = "HEALTH_ORB_TIER_2",
  HEALTH_ORB_TIER_3 = "HEALTH_ORB_TIER_3",
  BULLET_NECKLACE_TIER_1 = "BULLET_NECKLACE_TIER_1",
  BULLET_NECKLACE_TIER_2 = "BULLET_NECKLACE_TIER_2",
  BULLET_NECKLACE_TIER_3 = "BULLET_NECKLACE_TIER_3",
  LEAD_CLOAK_TIER_1 = "LEAD_CLOAK_TIER_1",
  LEAD_CLOAK_TIER_2 = "LEAD_CLOAK_TIER_2",
  LEAD_CLOAK_TIER_3 = "LEAD_CLOAK_TIER_3",
  VAMPIRE_RING_TIER_1 = "VAMPIRE_RING_TIER_1",
  CHAOS_CHALICE_TIER_1 = "CHAOS_CHALICE_TIER_1",
}
