import { POTION_TYPES } from "../../entities/consumables";
import { JUNK_TYPES } from "../../entities/junk";

export const CONSUMABLE_ITEMS = {};
export const FIRST_TIER_ITEMS = [];
export const SECONDS_TIER_ITEMS = [];
export const THIRD_TIER_ITEMS = [];

export const JUNK_DATA = {
  [JUNK_TYPES.AXE]: {
    price: 200,
    title: "Декоративный топорик",
  },
  [JUNK_TYPES.CRYSTAL_ORB]: {
    price: 300,
    title: "Кристальный шар",
  },
  [JUNK_TYPES.GOLDEN_CHAIN]: {
    price: 500,
    title: "Золотая цепочка",
  },
};

export const FIRST_TIER_JUNK = [JUNK_TYPES.AXE];
export const SECOND_TIER_JUNK = [JUNK_TYPES.CRYSTAL_ORB];
export const THIRD_TIER_JUNK = [JUNK_TYPES.GOLDEN_CHAIN];

export const POTION_TIERS = {
  [POTION_TYPES.SMALL_HEALTH_POTION]: 1,
  [POTION_TYPES.MEDIUM_HEALTH_POTION]: 2,
  [POTION_TYPES.LARGE_HEALTH_POTION]: 3,
  [POTION_TYPES.EXTRA_LARGE_HEALTH_POTION]: 4,
};

export const getPotionByTier = (currentTier: number) => {
  if (currentTier === 1) {
    return POTION_TYPES.SMALL_HEALTH_POTION;
  }

  if (currentTier === 2) {
    return POTION_TYPES.MEDIUM_HEALTH_POTION;
  }

  if (currentTier === 3) {
    return POTION_TYPES.LARGE_HEALTH_POTION;
  }

  return POTION_TYPES.EXTRA_LARGE_HEALTH_POTION;
};

export enum BASE_ITEMS_ID {
  BNTI_TIER_1 = "BNTI_TIER_1",
  NPP_TIER_1 = "NPP_TIER_1",
  BNTI_TIER_2 = "BNTI_TIER_2",
  BNTI_TIER_3 = "BNTI_TIER_3",
  NPP_TIER_2 = "NPP_TIER_2",
  NPP_TIER_3 = "NPP_TIER_3",
  IOTV_TIER_1 = "IOTV_TIER_1",
  IOTV_TIER_2 = "IOTV_TIER_2",
  IOTV_TIER_3 = "IOTV_TIER_3",
  FORT_TIER_1 = "FORT_TIER_1",
  FORT_TIER_2 = "FORT_TIER_2",
  FORT_TIER_3 = "FORT_TIER_3",
  NFM_TIER_1 = "NFM_TIER_1",
  NFM_TIER_2 = "NFM_TIER_2",
  NFM_TIER_3 = "NFM_TIER_3",
  REDUT_TIER_1 = "REDUT_TIER_1",
  REDUT_TIER_2 = "REDUT_TIER_2",
  REDUT_TIER_3 = "REDUT_TIER_3",
  SV98_TIER_1 = "SV98_TIER_1",
  SV98_TIER_2 = "SV98_TIER_2",
  SV98_TIER_3 = "SV98_TIER_3",
  DLV10_TIER_1 = "DLV10_TIER_1",
  DLV10_TIER_2 = "DLV10_TIER_2",
  DLV10_TIER_3 = "DLV10_TIER_3",
  AXMC_TIER_1 = "AXMC_TIER_1",
  AXMC_TIER_2 = "AXMC_TIER_2",
  AXMC_TIER_3 = "AXMC_TIER_3",
  MP155_TIER_1 = "MP155_TIER_1",
  MP155_TIER_2 = "MP155_TIER_2",
  MP155_TIER_3 = "MP155_TIER_3",
  REMINGTON_870_TIER_1 = "REMINGTON_870_TIER_1",
  REMINGTON_870_TIER_2 = "REMINGTON_870_TIER_2",
  REMINGTON_870_TIER_3 = "REMINGTON_870_TIER_3",
  SAIGA_TIER_1 = "SAIGA_TIER_1",
  SAIGA_TIER_2 = "SAIGA_TIER_2",
  SAIGA_TIER_3 = "SAIGA_TIER_3",
  AK_12_TIER_1 = "AK_12_TIER_1",
  AK_12_TIER_2 = "AK_12_TIER_2",
  AK_12_TIER_3 = "AK_12_TIER_3",
  M4A1_TIER_1 = "M4A1_TIER_1",
  M4A1_TIER_2 = "M4A1_TIER_2",
  M4A1_TIER_3 = "M4A1_TIER_3",
  SA58_TIER_1 = "SA58_TIER_1",
  SA58_TIER_2 = "SA58_TIER_2",
  SA58_TIER_3 = "SA58_TIER_3",
  MP5SD_TIER_1 = "MP5SD_TIER_1",
  MP5SD_TIER_2 = "MP5SD_TIER_2",
  MP5SD_TIER_3 = "MP5SD_TIER_3",
  FN_P90S_TIER_1 = "FN_P90S_TIER_1",
  FN_P90S_TIER_2 = "FN_P90S_TIER_2",
  FN_P90S_TIER_3 = "FN_P90S_TIER_3",
  KRISS_VECTOR_TIER_1 = "KRISS_VECTOR_TIER_1",
  KRISS_VECTOR_TIER_2 = "KRISS_VECTOR_TIER_2",
  KRISS_VECTOR_TIER_3 = "KRISS_VECTOR_TIER_3",
  GLOCK_17_TIER_1 = "GLOCK_17_TIER_1",
  GLOCK_17_TIER_2 = "GLOCK_17_TIER_2",
  GLOCK_17_TIER_3 = "GLOCK_17_TIER_3",
  FN_57_TIER_1 = "FN_57_TIER_1",
  FN_57_TIER_2 = "FN_57_TIER_2",
  FN_57_TIER_3 = "FN_57_TIER_3",
  DESERT_EAGLE_TIER_1 = "DESERT_EAGLE_TIER_1",
  DESERT_EAGLE_TIER_2 = "DESERT_EAGLE_TIER_2",
  DESERT_EAGLE_TIER_3 = "DESERT_EAGLE_TIER_3",
  RPD_TIER_1 = "RPD_TIER_1",
  RPD_TIER_2 = "RPD_TIER_2",
  RPD_TIER_3 = "RPD_TIER_3",
  M60_TIER_1 = "M60_TIER_1",
  M60_TIER_2 = "M60_TIER_2",
  M60_TIER_3 = "M60_TIER_3",
  PKM_TIER_1 = "PKM_TIER_1",
  PKM_TIER_2 = "PKM_TIER_2",
  PKM_TIER_3 = "PKM_TIER_3",

  HEALTH_ORB_TIER_1 = "HEALTH_ORB_TIER_1",
  BULLET_NECKLACE_TIER_1 = "BULLET_NECKLACE_TIER_1",
  LEAD_CLOAK_TIER_1 = "LEAD_CLOAK_TIER_1",
}
