import { create } from "zustand";
import { persist } from "zustand/middleware";

import { DEFAULT_GAME_STATE } from "../constants";

import { Battle, Enemy, StoreState } from "../../types/gameState";

import { persistConfig } from "./config";
import {
  healTeam,
  initiateState,
  resetGame,
  setEconomicBranch,
  setGameOver,
  turnOffDices,
  updateDialogFlags,
  setLocationState,
  setPlayerName,
  setState,
  changeAttempts,
  setQuestData,
  setBattleTurn,
  setReward,
  resetBattle,
  setSliders,
  updateGameTier,
  toggleInventory,
  toggleCharacterPanel,
  buyPotion,
  setDungeon,
  updateBattle,
  increaseAccuracy,
  increaseAgility,
  increaseEndurance,
  setPlayerPosition,
  buyCamera,
  sellJunk,
  addJunk,
  giveResources,
  updateFlags,
  increaseResourcesBagLevel,
  acquirePerk,
  sellItem,
  equipItem,
  handleExitDungeon,
  buyItem,
  generateDungeon,
  levelUpCharacter,
  consumePotion,
  buyTorches,
  updatePlayerState,
  setVolume,
  removeItemFromGear,
  handleExitSpecialEncounter,
  acquireArtifact,
  startSpecialEncounterGame,
  updateSpecialEncounter,
  resetQuest,
  craftItem,
  updateDungeon,
} from "./actions";

// Create the store
export const useGameState = create<StoreState>()(
  persist(
    (set) => ({
      // Initial state
      player: DEFAULT_GAME_STATE,
      effects: null,
      sell_inventory: null,
      inventory: null,
      statistics: null,
      gear: null,
      abilities: null,
      isDiceRequiredRoll: false,
      isAutoSaveRequired: false,
      playersLvlUpNotifications: [],

      // Methods

      updateDungeon: updateDungeon(set),
      updateDialogFlags: updateDialogFlags(set),
      setPlayerPosition: setPlayerPosition(set),
      increaseEndurance: increaseEndurance(set),
      consumePotion: consumePotion(set),
      acquireArtifact: acquireArtifact(set),
      setVolume: setVolume(set),
      resetQuest: resetQuest(set),
      generateDungeon: generateDungeon(set),
      increaseAccuracy: increaseAccuracy(set),
      updatePlayerState: updatePlayerState(set),
      removeItemFromGear: removeItemFromGear(set),
      updateFlags: updateFlags(set),
      increaseAgility: increaseAgility(set),
      craftItem: craftItem(set),
      handleExitSpecialEncounter: handleExitSpecialEncounter(set),
      updateSpecialEncounter: updateSpecialEncounter(set),
      startSpecialEncounterGame: startSpecialEncounterGame(set),
      updateBattle: updateBattle(set),
      setDungeon: setDungeon(set),
      changeAttempts: changeAttempts(set),
      setQuestData: setQuestData(set),
      equipItem: equipItem(set),
      setState: setState(set),
      setPlayerName: setPlayerName(set),
      setLocationState: setLocationState(set),
      setEconomicBranch: setEconomicBranch(set),
      healTeam: healTeam(set),
      turnOffDices: turnOffDices(set),
      setGameOver: setGameOver(set),
      levelUpCharacter: levelUpCharacter(set),
      initiateState: initiateState(set),
      resetGame: resetGame(set),
      buyTorches: buyTorches(set),
      setBattleTurn: setBattleTurn(set),
      setReward: setReward(set),
      resetBattle: resetBattle(set),
      setSliders: setSliders(set),
      updateGameTier: updateGameTier(set),
      buyPotion: buyPotion(set),
      toggleInventory: toggleInventory(set),
      buyCamera: buyCamera(set),
      toggleCharacterPanel: toggleCharacterPanel(set),
      increaseResourcesBagLevel: increaseResourcesBagLevel(set),
      acquirePerk: acquirePerk(set),
      sellJunk: sellJunk(set),
      addJunk: addJunk(set),
      sellItem: sellItem(set),
      giveResources: giveResources(set),
      handleExitDungeon: handleExitDungeon(set),
      buyItem: buyItem(set),

      // ф-ии чисто для тестов
      killEnemy: () =>
        set((state) => ({
          ...state,
          player: {
            ...state.player,
            battle: {
              ...(state.player.battle || ({} as Battle)),

              enemy: {
                ...(state.player.battle?.enemy || ({} as Enemy)),
                party: (state.player.battle?.enemy?.party || []).map(
                  (enemy) => ({ ...enemy, hp: 0 }),
                ),
              },
            },
          },
        })),
    }),
    persistConfig,
  ),
);
