export enum TURN_STATES {
  PLAYER_TURN = "PLAYER_TURN",
  ENEMY_TURN = "ENEMY_TURN",
}

export enum BATTLE_STATES {
  ENEMY_WIN = "ENEMY_WIN",
  PLAYER_WIN = "PLAYER_WIN",
  STILL_FIGHTING = "STILL_FIGHTING",
}

export enum BATTLE_TARGET {
  PLAYER = "PLAYER",
  ENEMY = "ENEMY",
}
