export enum CONSUMABLES {
  SMALL_HEALTH_POTION = "SMALL_HEALTH_POTION",
  MEDIUM_HEALTH_POTION = "MEDIUM_HEALTH_POTION",
  LARGE_HEALTH_POTION = "LARGE_HEALTH_POTION",
  EXTRA_LARGE_HEALTH_POTION = "EXTRA_LARGE_HEALTH_POTION",
}
