export enum DIALOGUE_FLAGS {
  ECONOMIC_INTRO = "ECONOMIC_INTRO",

  PRIEST_WELCOME = "PRIEST_WELCOME",
  BODY_PARTS = "BODY_PARTS",
  PHOTO = "PHOTO",
  CAMERA = "CAMERA",
  IMPROVE_BAG = "IMPROVE_BAG",
  SMITH_WELCOMED = "SMITH_WELCOMED",
}

export enum DIALOGUE_IDS {
  TAVERN_BUY = "TAVERN_BUY",
  TRADER_BUY = "TRADER_BUY",
  BUY_CAMERA = "BUY_CAMERA",
  ALMANAC = "ALMANAC",
  IMPROVE_BAG_INTRO = "IMPROVE_BAG_INTRO",
  BUY_BAG_IMPROVEMENT = "BUY_BAG_IMPROVEMENT",
  OPEN_SMITH = "OPEN_SMITH",
  RELEASE_ORE = "RELEASE_ORE",
  RELEASE_ORE_WITH_ARTIFACT = "RELEASE_ORE_WITH_ARTIFACT",
  RELEASE_PARTS = "RELEASE_PARTS",
  RELEASE_PARTS_WITH_ARTIFACT = "RELEASE_PARTS_WITH_ARTIFACT",
  RELEASE_TREASURES = "RELEASE_TREASURES",
  RELEASE_TREASURES_WITH_ARTIFACT = "RELEASE_TREASURES_WITH_ARTIFACT",
  BUY_TORCHES = "BUY_TORCHES",
  LEAVE_SPECIAL_ENCOUNTER_TRADER = "LEAVE_SPECIAL_ENCOUNTER_TRADER",
  BUY_LEGENDARY_ARMOR = "BUY_LEGENDARY_ARMOR",
  HEAL = "HEAL",
}
