export enum DIALOGUE_FLAGS {
  ECONOMIC_INTRO = "ECONOMIC_INTRO",
  HEAL = "HEAL",
  PRIEST_WELCOME = "PRIEST_WELCOME",
  BODY_PARTS = "BODY_PARTS",
  PHOTO = "PHOTO",
  CAMERA = "CAMERA",
  IMPROVE_BAG = "IMPROVE_BAG",
  SMITH_WELCOMED = "SMITH_WELCOMED",
}

export enum DIALOGUE_IDS {
  TAVERN_BUY = "TAVERN_BUY",
  TRADER_BUY = "TRADER_BUY",
  BUY_CAMERA = "BUY_CAMERA",
  ALMANAC = "ALMANAC",
  IMPROVE_BAG_INTRO = "IMPROVE_BAG_INTRO",
  BUY_BAG_IMPROVEMENT = "BUY_BAG_IMPROVEMENT",
  OPEN_SMITH = "OPEN_SMITH",
}
