export enum EFFECTS {
  BLEED = "BLEED",
  STUN = "STUN",
  FIRE = "FIRE",
  WEAKNESS = "WEAKNESS",
  HEAL_IMMUNE = "HEAL_IMMUNE",
  HEAL = "HEAL",
  BROKE = "BROKE",
  INSPIRED = "INSPIRED",
  INSTA_KILL_FATIGUE = "INSTA_KILL_FATIGUE",
}
