//
export enum ENEMIES {
  // противники локаций 1 тира
  SPIDER_TIER_1 = "SPIDER_TIER_1",
  SPIDER_TIER_2 = "SPIDER_TIER_2",
  SPIDER_TIER_3 = "SPIDER_TIER_3",

  TORSO_TIER_1 = "TORSO_TIER_1",
  TORSO_TIER_2 = "TORSO_TIER_2",
  TORSO_TIER_3 = "TORSO_TIER_3",

  WATCHER_TIER_1 = "WATCHER_TIER_1",
  WATCHER_TIER_2 = "WATCHER_TIER_2",
  WATCHER_TIER_3 = "WATCHER_TIER_3",

  SPIRIT_TIER_1 = "SPIRIT_TIER_1",
  SPIRIT_TIER_2 = "SPIRIT_TIER_2",
  SPIRIT_TIER_3 = "SPIRIT_TIER_3",

  BIRD_TIER_1 = "BIRD_TIER_1",
  BIRD_TIER_2 = "BIRD_TIER_2",
  BIRD_TIER_3 = "BIRD_TIER_3",

  SIN_ICON_TIER_1 = "SIN_ICON_TIER_1",

  // противники локаций 2 тира
  SOLDIER_TIER_1 = "SOLDIER_TIER_1",
  SOLDIER_TIER_2 = "SOLDIER_TIER_2",
  SOLDIER_TIER_3 = "SOLDIER_TIER_3",

  FIREFIGHTER_TIER_1 = "FIREFIGHTER_TIER_1",
  FIREFIGHTER_TIER_2 = "FIREFIGHTER_TIER_2",
  FIREFIGHTER_TIER_3 = "FIREFIGHTER_TIER_3",

  SNEAKER_TIER_1 = "SNEAKER_TIER_1",
  SNEAKER_TIER_2 = "SNEAKER_TIER_2",
  SNEAKER_TIER_3 = "SNEAKER_TIER_3",

  LOST_TIER_1 = "LOST_TIER_1",
  LOST_TIER_2 = "LOST_TIER_2",
  LOST_TIER_3 = "LOST_TIER_3",

  INVENTOR_TIER_1 = "INVENTOR_TIER_1",
  INVENTOR_TIER_2 = "INVENTOR_TIER_2",
  INVENTOR_TIER_3 = "INVENTOR_TIER_3",

  GENERAL_TIER_1 = "GENERAL_TIER_1",

  // противники локаций 3 тира

  ALL_SEEING_TIER_1 = "ALL_SEEING_TIER_1",
  ALL_SEEING_TIER_2 = "ALL_SEEING_TIER_2",
  ALL_SEEING_TIER_3 = "ALL_SEEING_TIER_3",

  KNIGHT_TIER_1 = "KNIGHT_TIER_1",
  KNIGHT_TIER_2 = "KNIGHT_TIER_2",
  KNIGHT_TIER_3 = "KNIGHT_TIER_3",

  ACTRESS_TIER_1 = "ACTRESS_TIER_1",
  ACTRESS_TIER_2 = "ACTRESS_TIER_2",
  ACTRESS_TIER_3 = "ACTRESS_TIER_3",

  SINGER_TIER_1 = "SINGER_TIER_1",
  SINGER_TIER_2 = "SINGER_TIER_2",
  SINGER_TIER_3 = "SINGER_TIER_3",

  BALLERINE_TIER_1 = "BALLERINE_TIER_1",
  BALLERINE_TIER_2 = "BALLERINE_TIER_2",
  BALLERINE_TIER_3 = "BALLERINE_TIER_3",

  MERGED_MASS_TIER_1 = "MERGED_MASS_TIER_1",
}

export enum ALMANAC_ENEMIES_GENERIC_TYPES {
  SPIDER = "SPIDER",
  TORSO = "TORSO",
  WATCHER = "WATCHER",
  SPIRIT = "SPIRIT",

  SOLDIER = "SOLDIER",
  FIREFIGHTER = "FIREFIGHTER",
  SNEAKER = "SNEAKER",
  LOST = "LOST",

  ALL_SEEING = "ALL_SEEING",
  ACTRESS = "ACTRESS",
  SINGER = "SINGER",
  KNIGHT = "KNIGHT",
}

export const FIRST_TIER_ALMANAC_ENEMIES_LIST = [
  ALMANAC_ENEMIES_GENERIC_TYPES.SPIDER,
  ALMANAC_ENEMIES_GENERIC_TYPES.TORSO,
  ALMANAC_ENEMIES_GENERIC_TYPES.WATCHER,
  ALMANAC_ENEMIES_GENERIC_TYPES.SPIRIT,
];

export const SECOND_TIER_ALMANAC_ENEMIES_LIST = [
  ALMANAC_ENEMIES_GENERIC_TYPES.SOLDIER,
  ALMANAC_ENEMIES_GENERIC_TYPES.FIREFIGHTER,
  ALMANAC_ENEMIES_GENERIC_TYPES.SNEAKER,
  ALMANAC_ENEMIES_GENERIC_TYPES.LOST,
];

export const THIRD_TIER_ALMANAC_ENEMIES_LIST = [
  ALMANAC_ENEMIES_GENERIC_TYPES.ALL_SEEING,
  ALMANAC_ENEMIES_GENERIC_TYPES.ACTRESS,
  ALMANAC_ENEMIES_GENERIC_TYPES.SINGER,
  ALMANAC_ENEMIES_GENERIC_TYPES.KNIGHT,
];
