// Это ENUM перечисления самих противников - эти значения можно мемоизировать и хранить в localStorage
// по ним мапимся для определения aipackage/assets

//
export enum ENEMIES {
  // противники локаций 1 тира
  SPIDER_TIER_1 = "SPIDER_TIER_1",
  SPIDER_TIER_2 = "SPIDER_TIER_2",
  SPIDER_TIER_3 = "SPIDER_TIER_3",
  TORSO_TIER_1 = "TORSO_TIER_1",
  TORSO_TIER_2 = "TORSO_TIER_2",
  TORSO_TIER_3 = "TORSO_TIER_3",
  WATCHER_TIER_1 = "WATCHER_TIER_1",
  WATCHER_TIER_2 = "WATCHER_TIER_2",
  WATCHER_TIER_3 = "WATCHER_TIER_3",
  SPIRIT_TIER_1 = "SPIRIT_TIER_1",
  SPIRIT_TIER_2 = "SPIRIT_TIER_2",
  SPIRIT_TIER_3 = "SPIRIT_TIER_3",

  BIRD_TIER_1 = "BIRD_TIER_1",
  BIRD_TIER_2 = "BIRD_TIER_2",
  BIRD_TIER_3 = "BIRD_TIER_3",

  SIN_ICON_TIER_1 = "SIN_ICON_TIER_1",

  // противники локаций 2 тира
  SOLDIER_TIER_1 = "SOLDIER_TIER_1",
  SOLDIER_TIER_2 = "SOLDIER_TIER_2",
  SOLDIER_TIER_3 = "SOLDIER_TIER_3",

  FIREFIGHTER_TIER_1 = "FIREFIGHTER_TIER_1",
  FIREFIGHTER_TIER_2 = "FIREFIGHTER_TIER_2",
  FIREFIGHTER_TIER_3 = "FIREFIGHTER_TIER_3",

  SNEAKER_TIER_1 = "SNEAKER_TIER_1",
  SNEAKER_TIER_2 = "SNEAKER_TIER_2",
  SNEAKER_TIER_3 = "SNEAKER_TIER_3",

  LOST_TIER_1 = "LOST_TIER_1",
  LOST_TIER_2 = "LOST_TIER_2",
  LOST_TIER_3 = "LOST_TIER_3",

  INVENTOR_TIER_1 = "INVENTOR_TIER_1",
  INVENTOR_TIER_2 = "INVENTOR_TIER_2",
  INVENTOR_TIER_3 = "INVENTOR_TIER_3",

  GENERAL_TIER_1 = "GENERAL_TIER_1",
}
