export enum RENDER_LOCATIONS {
  SETTLEMENT = "SETTLEMENT",
  DUNGEON = "DUNGEON",
  BATTLE = "BATTLE",
  INVENTORY = "INVENTORY",
  LEVELING = "LEVELING",
  SPECIAL_ENCOUNTER = "SPECIAL_ENCOUNTER",
}
