import { GUN_TYPES } from "../../entities/guns";
import { CLASSES } from "../../entities/characterClasses";

export const TANK_ALLOWED_GUNS = [GUN_TYPES.MACHINE_GUN, GUN_TYPES.SHOTGUN];
export const MEDIC_ALLOWED_GUNS = [GUN_TYPES.PISTOL, GUN_TYPES.SMG];
export const SNIPER_ALLOWED_GUNS = [
  GUN_TYPES.ASSAULT_RIFLE,
  GUN_TYPES.SNIPER_RIFLE,
];

export const CLASS_GUN_RESTRICTIONS = {
  [CLASSES.TANK]: TANK_ALLOWED_GUNS,
  [CLASSES.MEDIC]: MEDIC_ALLOWED_GUNS,
  [CLASSES.SNIPER]: SNIPER_ALLOWED_GUNS,
};
