import {
  BNTI_TIER_1,
  BNTI_TIER_2,
  BNTI_TIER_3,
  FORT_TIER_1,
  FORT_TIER_2,
  FORT_TIER_3,
  IOTV_TIER_1,
  IOTV_TIER_2,
  IOTV_TIER_3,
  NFM_TIER_1,
  NFM_TIER_2,
  NFM_TIER_3,
  NPP_TIER_1,
  NPP_TIER_2,
  NPP_TIER_3,
  REDUT_TIER_1,
  REDUT_TIER_2,
  REDUT_TIER_3,
} from "../constants/armor";
import { SNIPER_TIER_1 } from "../constants/guns";
import { BASE_ITEMS_ID } from "../constants/items";
import { Item } from "../types/gameState";

const BASE_ITEM_TIER_BY_TYPE_MAP = {
  [BASE_ITEMS_ID.SNIPER_TIER_1]: SNIPER_TIER_1,
  [BASE_ITEMS_ID.BNTI_TIER_1]: BNTI_TIER_1,
  [BASE_ITEMS_ID.NPP_TIER_1]: NPP_TIER_1,
  [BASE_ITEMS_ID.BNTI_TIER_2]: BNTI_TIER_2,
  [BASE_ITEMS_ID.BNTI_TIER_3]: BNTI_TIER_3,
  [BASE_ITEMS_ID.NPP_TIER_2]: NPP_TIER_2,
  [BASE_ITEMS_ID.NPP_TIER_3]: NPP_TIER_3,
  [BASE_ITEMS_ID.IOTV_TIER_1]: IOTV_TIER_1,
  [BASE_ITEMS_ID.IOTV_TIER_2]: IOTV_TIER_2,
  [BASE_ITEMS_ID.IOTV_TIER_3]: IOTV_TIER_3,
  [BASE_ITEMS_ID.FORT_TIER_1]: FORT_TIER_1,
  [BASE_ITEMS_ID.FORT_TIER_2]: FORT_TIER_2,
  [BASE_ITEMS_ID.FORT_TIER_3]: FORT_TIER_3,
  [BASE_ITEMS_ID.NFM_TIER_1]: NFM_TIER_1,
  [BASE_ITEMS_ID.NFM_TIER_2]: NFM_TIER_2,
  [BASE_ITEMS_ID.NFM_TIER_3]: NFM_TIER_3,
  [BASE_ITEMS_ID.REDUT_TIER_1]: REDUT_TIER_1,
  [BASE_ITEMS_ID.REDUT_TIER_2]: REDUT_TIER_2,
  [BASE_ITEMS_ID.REDUT_TIER_3]: REDUT_TIER_3,
};

export const getBaseItemByBaseId = (
  baseItemId: BASE_ITEMS_ID,
): Omit<Item, "gearId"> => BASE_ITEM_TIER_BY_TYPE_MAP[baseItemId];
