import {
  BUILDING_NAMES,
  FIRST_TIER_ARTIFACT_RESOURCES_AMOUNT,
  FLAGS,
  SECOND_TIER_ARTIFACT_RESOURCES_AMOUNT,
  THIRD_TIER_ARTIFACT_RESOURCES_AMOUNT,
} from "../constants";

export const getRequiredResourcesAmount = (
  flags: FLAGS,
  npc: BUILDING_NAMES,
) => {
  if (npc === BUILDING_NAMES.SMITH) {
    if (flags.includes(FLAGS.SMITH_ARTIFACT_ACHIEVED_TIER_1)) {
      return SECOND_TIER_ARTIFACT_RESOURCES_AMOUNT;
    }

    if (flags.includes(FLAGS.SMITH_ARTIFACT_ACHIEVED_TIER_2)) {
      return THIRD_TIER_ARTIFACT_RESOURCES_AMOUNT;
    }

    return FIRST_TIER_ARTIFACT_RESOURCES_AMOUNT;
  }

  if (npc === BUILDING_NAMES.TAVERN) {
    if (flags.includes(FLAGS.ALCHEMISTRY_ARTIFACT_ACHIEVED_TIER_1)) {
      return SECOND_TIER_ARTIFACT_RESOURCES_AMOUNT;
    }

    if (flags.includes(FLAGS.ALCHEMISTRY_ARTIFACT_ACHIEVED_TIER_2)) {
      return THIRD_TIER_ARTIFACT_RESOURCES_AMOUNT;
    }

    return FIRST_TIER_ARTIFACT_RESOURCES_AMOUNT;
  }

  // 3 вариант - всегда MEDICAL_STATION
  if (flags.includes(FLAGS.PRIEST_ARTIFACT_ACHIEVED_TIER_1)) {
    return SECOND_TIER_ARTIFACT_RESOURCES_AMOUNT;
  }

  if (flags.includes(FLAGS.PRIEST_ARTIFACT_ACHIEVED_TIER_2)) {
    return THIRD_TIER_ARTIFACT_RESOURCES_AMOUNT;
  }

  return FIRST_TIER_ARTIFACT_RESOURCES_AMOUNT;
};
